### PR TITLE
Misc fixes to make the linter happier and go to level 7 ?

### PR DESCRIPTION
**Pull request by alexAubin**
Randomly passing by seeing the app is stuck at level 4 because of things easy to fix so here's a pull request o/

~~Test ongoing here : https://ci-apps-dev.yunohost.org/jenkins/job/ihatemoney_ynh%20(aleks)/1/console~~

App is level 7 on last build here : https://ci-apps-dev.yunohost.org/jenkins/view/aleks/job/ihatemoney_ynh%20(aleks)/4/console

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
Great, thanks for the cleanup !

OK, i'd like to be sure edits are tested before mergin' ; did you tested the edits on a real install ?

Otherwise, I'll wait to take time to test before mergin.

**Comment by alexAubin** [comment]
@JocelynDelalande : hmmmwell the tests already validate that the app is indeed reachable (by curling https://domain.tld/theapp and checking the page content corresponds to the app). But that never replace an actual human testing the app ;) 

I'm fixing some other minor things in the meantime, and I notice the tests report this error : 

```
Error: : ihatemoney 4.1.4 has requirement Werkzeug==0.16.1, but you'll have werkzeug 0.16.0 which is incompatible.
```

probably during the pip install ... does that mean anything to you ? (that doesn't seem to prevent the app from working though ?)

**Comment by alexAubin** [comment]
(App is level 7 on last build here : https://ci-apps-dev.yunohost.org/jenkins/view/aleks/job/ihatemoney_ynh%20(aleks)/4/console )

**Comment by JocelynDelalande** [comment]
> (App is level 7 on last build here : https://ci-apps-dev.yunohost.org/jenkins/view/aleks/job/ihatemoney_ynh%20(aleks)/4/console )

404 error, just to let u know :)

**Comment by JocelynDelalande** [comment]
Tested everything I could think about, and it works !

**Comment by JocelynDelalande** [comment]
Thanks @alexAubin <3

**Comment by alexAubin** [comment]
Zblerg not sure what happens with the links, looks like jenkins was upgraded or something, right link is https://ci-apps-dev.yunohost.org/jenkins/job/ihatemoney_ynh%20(aleks)/4/console

Thanks for the merge !

**Pull request merged**
